### ISSUE TITLE
Error in npm i git-ftp

### ISSUE THREAD

**Issue by ritsrivastava01** [git-ftp/git-ftp#569]
Dear All,
 I'm facing the issue while installing "git-ftp" in my application:
var args = func.toString().match(/function\s.*?\(([^)]*)\)/)[1];
                                                              ^

TypeError: Cannot read property '1' of null
    at module.exports (test_fe/node_modules/promisify-node/utils/args.js:9:63)
    at /test_fe/node_modules/promisify-node/index.js:79:29
    at Array.filter (<anonymous>)
    at processExports (/test_fe/node_modules/promisify-node/index.js:60:6)
    at module.exports (/test_fe/node_modules/promisify-node/index.js:112:10)
    at Object.<anonymous> (/test_fe/node_modules/nodegit/generate/scripts/generateNativeCode.js:3:13)

Any Idea, how to install the git-ftp??

Ritz

**Comment by LukasFritzeDev** [comment]
Hey, this is not the node package, its a bash cli tool to upload files to a ftp server using some git utils. So maybe you should contact the developer of the node package.
